import {SNSEvent , Context } from 'aws-lambda';

export async function handler(event: SNSEvent, context: Context){

  // logging the event generated by SNS and to see message clearly
  console.log(event.Records[0].Sns)
 
}